[build]
# pretty much same as default (x86-64)
# rustflags = ["-C", "target-cpu=x86-64-v2"]

# best results, prefetching doesn't help anymore
# rustflags = ["-C", "target-cpu=x86-64-v3"]

# some weird behavior
# rustflags = ["-C", "target-cpu=x86-64-v4"]

# similar to x86-64-v4
rustflags = ["-C", "target-cpu=native"]
